# Site settings
title: devinmatte.me
email: devin@devinmatte.com
author: Devin Matte
description: "Devin Matte's Blog for posting about everything I'm learning about, and want to talk about"
baseurl: ""
url: "https://devinmatte.me"
date_format: "%b %-d, %Y"
default-image: "/images/devinmatte.jpg"

# Google services
google_analytics: UA-90401650-1
google_verification: dp-IySBoAuap8dvxEM4kQND6f_DV7BW5-g5a-bNM2bw

# Optional features
animated:             false
show_related_posts:   false
show_post_footers:    false
show_social_icons:    false
ajaxify_contact_form: false
enable_mathjax: false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Facebook Comments plugin
# (leave blank to disable Facebook Comments, otherwise set it to true)
facebook_comments:
facebook_appid:
facebook_comments_number: 10

# Social icons
github_username: "devinmatte"
bitbucket_username:
stackoverflow_id: "5863087"
twitter_username: "devinmatte"
skype_username:
steam_nickname:
google_plus_id:
linkedin_username: "devin-m-5556a386"
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: false
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: true
share_stumbleupon: false
share_hackernews: true

text:
  pagination:
    newer: 'Newer'
    older: 'Older'
  share_buttons:
    text:         'Like this? Share it!'
    facebook:     'Share on Facebook'
    twitter:      'Share on Twitter'
    googleplus:   'Share on Google+'
    linkedin:     'Share on LinkedIn'
    digg:         'Share on Digg'
    tumblr:       'Share on Tumblr'
    reddit:       'Share on Reddit'
    stumbleupon:  'Share on StumbleUpon'
    hackernews:   'Share on Hacker News'
  post:
    updated:        'Updated'
    minute_read:    'minute read'
    related_posts:  'Related Posts'
  index:
    coming_soon: 'Coming soon...'
  contact:
    email:    'Email Address'
    content:  'What would you like to say?'
    subject:  'New submission!'
    submit:   'Say Hello'
    ajax:
      sending:  'sending..'
      sent:     'Message sent!'
      error:    'Error!'
  thanks: 'Thanks for contacting us. We will reply as soon as possible.'


# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["tables", "fenced_code_blocks"]
permalink: pretty
paginate: 10
